// Dummy data only. Replace this with SharePoint or API data later.
const students = [
  { id: 'HELP-001', name: 'Ahmad Reza Karimi', nationality: 'Iranian', faculty: 'Business and Economics', programme: 'MBA Business Administration', requiredDays: 240, verifiedDays: 208, lastSubmission: '10 Sep 2026', status: 'warning', issues: ['32 stay days still required'], records: [{ type: 'Entry', date: '12 Aug 2026', status: 'Verified', days: 29 }, { type: 'Exit', date: '14 Jul 2026', status: 'Verified', days: 0 }] },
  { id: 'HELP-002', name: 'Li Xiao Wei', nationality: 'Chinese', faculty: 'Computing and Digital Technology', programme: 'BSc Computer Science', requiredDays: 365, verifiedDays: 316, lastSubmission: '14 Sep 2026', status: 'compliant', issues: [], records: [{ type: 'Entry', date: '14 Sep 2026', status: 'Verified', days: 14 }, { type: 'Exit', date: '31 Aug 2026', status: 'Verified', days: 0 }] },
  { id: 'HELP-003', name: 'Priya Nair Subramaniam', nationality: 'Indian', faculty: 'Social Sciences and Liberal Arts', programme: 'BA Psychology', requiredDays: 300, verifiedDays: 192, lastSubmission: '22 Jul 2026', status: 'non-compliant', issues: ['No new travel declaration for 64 days', '108 stay days still required'], records: [{ type: 'Entry', date: '22 Jul 2026', status: 'Verified', days: 64 }, { type: 'Exit', date: '20 May 2026', status: 'Verified', days: 0 }] },
  { id: 'HELP-004', name: 'Mohammed Al-Hassan', nationality: 'Saudi Arabian', faculty: 'Business and Economics', programme: 'BBA Finance', requiredDays: 240, verifiedDays: 173, lastSubmission: '01 Sep 2026', status: 'warning', issues: ['Travel declaration is pending review', '67 stay days still required'], records: [{ type: 'Entry', date: '01 Sep 2026', status: 'Pending', days: 0 }, { type: 'Exit', date: '10 Aug 2026', status: 'Verified', days: 0 }] },
  { id: 'HELP-005', name: 'Fatima Osei Mensah', nationality: 'Ghanaian', faculty: 'Law', programme: 'LLB', requiredDays: 365, verifiedDays: 344, lastSubmission: '15 Sep 2026', status: 'compliant', issues: [], records: [{ type: 'Entry', date: '15 Sep 2026', status: 'Verified', days: 15 }, { type: 'Exit', date: '30 Aug 2026', status: 'Verified', days: 0 }] },
  { id: 'HELP-006', name: 'Tomasz Kowalski', nationality: 'Polish', faculty: 'Computing and Digital Technology', programme: 'BSc Software Engineering', requiredDays: 365, verifiedDays: 201, lastSubmission: '10 Jun 2026', status: 'non-compliant', issues: ['Travel record awaiting correction', '164 stay days still required'], records: [{ type: 'Exit', date: '10 Jun 2026', status: 'Rejected', days: 0 }, { type: 'Entry', date: '01 May 2026', status: 'Verified', days: 40 }] },
];
const faculties = [...new Set(students.map((student) => student.faculty))];
